"""auto-vote

Revision ID: 108e0118b7f0
Revises: ce909b0dbf1a
Create Date: 2025-03-08 00:21:10.644524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108e0118b7f0'
down_revision: Union[str, None] = 'ce909b0dbf1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('votes', sa.Column('user_id', sa.Integer(), nullable=False), 
                    sa.Column('post_id', sa.Integer(), nullable=False), 
sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),

                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),

                    sa.PrimaryKeyConstraint('user_id', 'post_id'))
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('votes')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
