"""Recreate posts table

Revision ID: ed2014743d74
Revises: 0ed3e0a70e93
Create Date: 2025-03-07 18:59:21.477075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2014743d74'
down_revision: Union[str, None] = '0ed3e0a70e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(), nullable=False),
    # sa.Column('password', sa.String(), nullable=False),
    # sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email')
    # )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False)
    )
    # op.create_table('votes',
    # sa.Column('post_id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('post_id', 'user_id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('posts')
    # ### end Alembic commands ###




